services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: yarn dev
    env_file:
      - ./apps/reservations/.env
    ports:
      - 4444:4444
    volumes:
      - .:/usr/src/app
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - 4001:4001
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017